src/draw.c: always use "%s"-style format for printf()-style functions
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    src/draw.c:235:9: error: format not a string literal and no format arguments [-Werror=format-security]
      235 |         mvwprintw(board_win, center, left+1, tile_str[val]);
          |         ^~~~~~~~~

Let's wrap all the missing places with "%s" format.